In [11]:
import cv2
import numpy as np

img = cv2.imread('E:/Pawang Code/Diabetic Retinopathy/dataset/0/3bf3085ac167.png')
img = cv2.resize(img, (512, 512))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
mask = img>7

ix = np.ix_(mask.any(1),mask.any(0))
tes = img[ix]
  
print (tes)

[[2 2 2 ... 1 1 2]
 [1 1 1 ... 1 1 2]
 [0 0 0 ... 1 1 2]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
