In [2]:
import numpy as np
from PIL import Image
import cv2
from tqdm import tqdm
import pandas as pd
from keras.models import Sequential
from keras import layers
from keras.optimizers import Adam
from keras.applications import DenseNet121

In [1]:
print('tes')

tes


In [4]:
densenet = DenseNet121(
  weights='C:/Users/Bangik/Documents/python/diabetic-retinopathy-ml/model/DenseNet-BC-121-32-no-top.h5',
  include_top=False,
  input_shape=(224,224,3)
)

def build_model():
  model = Sequential()
  model.add(densenet)
  model.add(layers.GlobalAveragePooling2D())
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(5, activation='sigmoid'))
  
  model.compile(
      loss='binary_crossentropy',
      optimizer=Adam(lr=0.00005),
      metrics=['accuracy']
  )
  
  return model

model = build_model()
model.load_weights('C:/Users/Bangik/Documents/python/diabetic-retinopathy-ml/model/model-cnn-idrid-22-5-23.h5')

c:\Users\Bangik\Documents\python\diabetic-retinopathy-ml\venv\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [5]:
def crop_image_from_gray(img,tol=7):
  if img.ndim ==2:
    mask = img>tol
    return img[np.ix_(mask.any(1),mask.any(0))]
  elif img.ndim==3:
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    mask = gray_img>tol        
    check_shape = img[:,:,0][np.ix_(mask.any(1),mask.any(0))].shape[0]
    if (check_shape == 0):
      return img
    else:
      img1=img[:,:,0][np.ix_(mask.any(1),mask.any(0))]
      img2=img[:,:,1][np.ix_(mask.any(1),mask.any(0))]
      img3=img[:,:,2][np.ix_(mask.any(1),mask.any(0))]
      img = np.stack([img1,img2,img3],axis=-1)
      return img

def circle_crop_v2(img):
  img = crop_image_from_gray(img)

  height, width, depth = img.shape
  largest_side = np.max((height, width))
  img = cv2.resize(img, (largest_side, largest_side))

  height, width, depth = img.shape

  x = int(width / 2)
  y = int(height / 2)
  r = np.amin((x, y))

  circle_img = np.zeros((height, width), np.uint8)
  cv2.circle(circle_img, (x, y), int(r), 1, thickness=-1)
  img = cv2.bitwise_and(img, img, mask=circle_img)
  img = crop_image_from_gray(img)

  return img

def preprocess_image(image_path, desired_size=224):
  img = cv2.imread(image_path)
  circle_crop = circle_crop_v2(img)
  bgr2rgb = cv2.cvtColor(circle_crop, cv2.COLOR_BGR2RGB)
  img_pil = Image.fromarray(bgr2rgb)
  im = img_pil.resize((desired_size, )*2, resample=Image.LANCZOS)
  return im

def prediction(image_path):
  tes_image = np.empty((1, 224, 224, 3), dtype=np.uint8)
  tes_image[0, :, :, :] = preprocess_image(image_path)
  predicted = model.predict(tes_image, verbose=None)
  probability = predicted.max()
  predicted = predicted > 0.5
  predicted = predicted.astype(int).sum(axis=1) - 1
  return predicted[0], probability

In [33]:
path_image = "E:/Pawang Code/Diabetic Retinopathy/Databases acquired by Service dOphtalmologie Hôpital Lariboisière Paris Messidor/Base11/20051020_43808_0100_PP.tif"
pil = Image.open(path_image).convert('RGB')
cv2image = np.array(pil)
tes = prediction(cv2image)
print(tes[0])

1/1 [==============================] - 6s 6s/step
0


In [ ]:
train_df = pd.read_csv('E:/Pawang Code/Diabetic Retinopathy/Diabetic Retinopathy Detection competition kaggle/trainLabels.csv')
filename = []
y_true = []
y_pred = []

for i, image_id in enumerate(train_df.values):
  path_image = "E:/Pawang Code/Diabetic Retinopathy/Diabetic Retinopathy Detection competition kaggle/train/{}.jpeg".format(image_id[0])
  try:
    pil = Image.open(path_image).convert('RGB')
    cv2image = np.array(pil)
    tes = prediction(cv2image)
    filename.append(image_id[0])
    y_pred.append(tes[0])
    y_true.append(image_id[1])
  except:
    continue


In [7]:
# list to csv
df = pd.DataFrame({'y_pred': y_pred})
df.to_csv('E:/Pawang Code/Diabetic Retinopathy/Diabetic Retinopathy Detection competition kaggle/result.csv', index=False)

In [9]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.95      0.86       567
           1       0.04      0.02      0.02        56
           2       0.31      0.10      0.15       110
           3       0.38      0.14      0.21        21
           4       0.40      0.14      0.21        14

    accuracy                           0.73       768
   macro avg       0.38      0.27      0.29       768
weighted avg       0.64      0.73      0.66       768

[[540  15  10   1   1]
 [ 54   1   1   0   0]
 [ 90   6  11   2   1]
 [  8   2   7   3   1]
 [  3   1   6   2   2]]


In [9]:
tes = prediction('E:/Pawang Code/Diabetic Retinopathy/INDIAN DIABETIC RETINOPATHY IMAGE DATASET/B. Disease Grading/1. Original Images/a. Training Set/IDRiD_001.jpg')
print(tes[0])

2


In [9]:
train_df = pd.read_csv('E:/Pawang Code/Diabetic Retinopathy/INDIAN DIABETIC RETINOPATHY IMAGE DATASET/B. Disease Grading/2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv')
dictDataframe = {'id_code': [], 'diagnosis': [], 'predicted': []}

for i, image_id in enumerate(tqdm(train_df.values)):
    image_path = 'E:/Pawang Code/Diabetic Retinopathy/INDIAN DIABETIC RETINOPATHY IMAGE DATASET/B. Disease Grading/1. Original Images/a. Training Set/{}.jpg'.format(image_id[0])
    tes = prediction(image_path)
    dictDataframe['id_code'].append(image_id[0])
    dictDataframe['diagnosis'].append(image_id[1])
    dictDataframe['predicted'].append(tes[0])
    # print(i, image_id[0], tes[0], tes[1])

# df = pd.DataFrame(dictDataframe)
# df.to_csv('E:/Pawang Code/Diabetic Retinopathy/INDIAN DIABETIC RETINOPATHY IMAGE DATASET/B. Disease Grading/tes_prediction.csv', index=False)

100%|██████████| 413/413 [12:09<00:00,  1.77s/it]


In [10]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
df = pd.DataFrame(dictDataframe)
print(classification_report(df['diagnosis'], df['predicted']))
print(confusion_matrix(df['diagnosis'], df['predicted']))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82       134
           1       0.26      0.30      0.28        20
           2       0.76      0.76      0.76       136
           3       0.64      0.66      0.65        74
           4       0.74      0.71      0.73        49

    accuracy                           0.73       413
   macro avg       0.65      0.65      0.65       413
weighted avg       0.73      0.73      0.73       413

[[108  12  13   1   0]
 [ 12   6   2   0   0]
 [ 10   5 103  17   1]
 [  0   0  14  49  11]
 [  0   0   4  10  35]]
